-- MySQL Script generated by MySQL Workbench
-- Mon Nov 12 20:13:11 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Story`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Story` (
  `id` INT NOT NULL,
  `title` VARCHAR(250) NOT NULL,
  `title_jpn` VARCHAR(250) NOT NULL,
  `description` VARCHAR(750) NULL,
  `author` VARCHAR(300) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `birthdate` DATETIME NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `jpn_lvl` INT NULL,
  `datejoined` DATETIME NOT NULL,
  `status` INT NOT NULL DEFAULT 1,
  `profile_msg` VARCHAR(1000) NULL,
  `gender` INT NULL DEFAULT 0,
  `profile_pic` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Chapter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Chapter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `title_jpn` VARCHAR(200) NULL,
  `Story_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Chapter_Story1_idx` (`Story_id` ASC),
  CONSTRAINT `fk_Chapter_Story1`
    FOREIGN KEY (`Story_id`)
    REFERENCES `mydb`.`Story` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grammar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grammar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `explanation` VARCHAR(5000) NOT NULL,
  `Chapter_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Grammar_Chapter1_idx` (`Chapter_id` ASC),
  CONSTRAINT `fk_Grammar_Chapter1`
    FOREIGN KEY (`Chapter_id`)
    REFERENCES `mydb`.`Chapter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Word`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Word` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` INT NOT NULL,
  `word` VARCHAR(300) NOT NULL,
  `meaning_eng` VARCHAR(300) NOT NULL,
  `hiragana` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SentencePiece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SentencePiece` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sentence_id` INT NOT NULL,
  `piece` VARCHAR(1000) NOT NULL,
  `meaning_eng` VARCHAR(1000) NOT NULL,
  `type` INT NOT NULL,
  `parent_piece` INT NULL,
  `Chapter_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_SentencePiece_Chapter1_idx` (`Chapter_id` ASC),
  CONSTRAINT `fk_SentencePiece_Chapter1`
    FOREIGN KEY (`Chapter_id`)
    REFERENCES `mydb`.`Chapter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Scores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Scores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `User_id` INT NOT NULL,
  `quiz_type` INT NOT NULL,
  `score` INT NOT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Activity_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Activity_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SentenceWord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SentenceWord` (
  `SentencePiece_id` INT NOT NULL,
  `Word_id` INT NOT NULL,
  INDEX `fk_SentenceWord_SentencePiece1_idx` (`SentencePiece_id` ASC),
  INDEX `fk_SentenceWord_Word1_idx` (`Word_id` ASC),
  CONSTRAINT `fk_SentenceWord_SentencePiece1`
    FOREIGN KEY (`SentencePiece_id`)
    REFERENCES `mydb`.`SentencePiece` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SentenceWord_Word1`
    FOREIGN KEY (`Word_id`)
    REFERENCES `mydb`.`Word` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Questions` (
  `id` INT NOT NULL,
  `question` VARCHAR(500) NOT NULL,
  `type` INT NOT NULL,
  `options` VARCHAR(5000) NOT NULL,
  `answer` VARCHAR(500) NOT NULL,
  `Story_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Questions_Story1_idx` (`Story_id` ASC),
  CONSTRAINT `fk_Questions_Story1`
    FOREIGN KEY (`Story_id`)
    REFERENCES `mydb`.`Story` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Feedback` (
  `id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Feedback_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Feedback_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
